// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/data/dto.proto

package dto;

public final class ProtoDTO {
  private ProtoDTO() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:data.User)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>required string login = 2;</code>
     */
    boolean hasLogin();
    /**
     * <code>required string login = 2;</code>
     */
    String getLogin();
    /**
     * <code>required string login = 2;</code>
     */
    com.google.protobuf.ByteString
        getLoginBytes();

    /**
     * <code>repeated string birthday = 3;</code>
     */
    java.util.List<String>
        getBirthdayList();
    /**
     * <code>repeated string birthday = 3;</code>
     */
    int getBirthdayCount();
    /**
     * <code>repeated string birthday = 3;</code>
     */
    String getBirthday(int index);
    /**
     * <code>repeated string birthday = 3;</code>
     */
    com.google.protobuf.ByteString
        getBirthdayBytes(int index);

    /**
     * <code>repeated string birthplace = 4;</code>
     */
    java.util.List<String>
        getBirthplaceList();
    /**
     * <code>repeated string birthplace = 4;</code>
     */
    int getBirthplaceCount();
    /**
     * <code>repeated string birthplace = 4;</code>
     */
    String getBirthplace(int index);
    /**
     * <code>repeated string birthplace = 4;</code>
     */
    com.google.protobuf.ByteString
        getBirthplaceBytes(int index);

    /**
     * <code>repeated string hobbies = 5;</code>
     */
    java.util.List<String>
        getHobbiesList();
    /**
     * <code>repeated string hobbies = 5;</code>
     */
    int getHobbiesCount();
    /**
     * <code>repeated string hobbies = 5;</code>
     */
    String getHobbies(int index);
    /**
     * <code>repeated string hobbies = 5;</code>
     */
    com.google.protobuf.ByteString
        getHobbiesBytes(int index);
  }
  /**
   * Protobuf type {@code data.User}
   */
  public  static final class User extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:data.User)
      UserOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private User() {
      id_ = 0;
      login_ = "";
      birthday_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      birthplace_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      hobbies_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private User(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              login_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                birthday_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              birthday_.add(bs);
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                birthplace_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              birthplace_.add(bs);
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                hobbies_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000010;
              }
              hobbies_.add(bs);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          birthday_ = birthday_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          birthplace_ = birthplace_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          hobbies_ = hobbies_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoDTO.internal_static_data_User_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoDTO.internal_static_data_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              User.class, Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int LOGIN_FIELD_NUMBER = 2;
    private volatile Object login_;
    /**
     * <code>required string login = 2;</code>
     */
    public boolean hasLogin() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string login = 2;</code>
     */
    public String getLogin() {
      Object ref = login_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          login_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string login = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLoginBytes() {
      Object ref = login_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        login_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BIRTHDAY_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList birthday_;
    /**
     * <code>repeated string birthday = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getBirthdayList() {
      return birthday_;
    }
    /**
     * <code>repeated string birthday = 3;</code>
     */
    public int getBirthdayCount() {
      return birthday_.size();
    }
    /**
     * <code>repeated string birthday = 3;</code>
     */
    public String getBirthday(int index) {
      return birthday_.get(index);
    }
    /**
     * <code>repeated string birthday = 3;</code>
     */
    public com.google.protobuf.ByteString
        getBirthdayBytes(int index) {
      return birthday_.getByteString(index);
    }

    public static final int BIRTHPLACE_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList birthplace_;
    /**
     * <code>repeated string birthplace = 4;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getBirthplaceList() {
      return birthplace_;
    }
    /**
     * <code>repeated string birthplace = 4;</code>
     */
    public int getBirthplaceCount() {
      return birthplace_.size();
    }
    /**
     * <code>repeated string birthplace = 4;</code>
     */
    public String getBirthplace(int index) {
      return birthplace_.get(index);
    }
    /**
     * <code>repeated string birthplace = 4;</code>
     */
    public com.google.protobuf.ByteString
        getBirthplaceBytes(int index) {
      return birthplace_.getByteString(index);
    }

    public static final int HOBBIES_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList hobbies_;
    /**
     * <code>repeated string hobbies = 5;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getHobbiesList() {
      return hobbies_;
    }
    /**
     * <code>repeated string hobbies = 5;</code>
     */
    public int getHobbiesCount() {
      return hobbies_.size();
    }
    /**
     * <code>repeated string hobbies = 5;</code>
     */
    public String getHobbies(int index) {
      return hobbies_.get(index);
    }
    /**
     * <code>repeated string hobbies = 5;</code>
     */
    public com.google.protobuf.ByteString
        getHobbiesBytes(int index) {
      return hobbies_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLogin()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, login_);
      }
      for (int i = 0; i < birthday_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, birthday_.getRaw(i));
      }
      for (int i = 0; i < birthplace_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, birthplace_.getRaw(i));
      }
      for (int i = 0; i < hobbies_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, hobbies_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, login_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < birthday_.size(); i++) {
          dataSize += computeStringSizeNoTag(birthday_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getBirthdayList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < birthplace_.size(); i++) {
          dataSize += computeStringSizeNoTag(birthplace_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getBirthplaceList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < hobbies_.size(); i++) {
          dataSize += computeStringSizeNoTag(hobbies_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getHobbiesList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof User)) {
        return super.equals(obj);
      }
      User other = (User) obj;

      boolean result = true;
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && (getId()
            == other.getId());
      }
      result = result && (hasLogin() == other.hasLogin());
      if (hasLogin()) {
        result = result && getLogin()
            .equals(other.getLogin());
      }
      result = result && getBirthdayList()
          .equals(other.getBirthdayList());
      result = result && getBirthplaceList()
          .equals(other.getBirthplaceList());
      result = result && getHobbiesList()
          .equals(other.getHobbiesList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
      }
      if (hasLogin()) {
        hash = (37 * hash) + LOGIN_FIELD_NUMBER;
        hash = (53 * hash) + getLogin().hashCode();
      }
      if (getBirthdayCount() > 0) {
        hash = (37 * hash) + BIRTHDAY_FIELD_NUMBER;
        hash = (53 * hash) + getBirthdayList().hashCode();
      }
      if (getBirthplaceCount() > 0) {
        hash = (37 * hash) + BIRTHPLACE_FIELD_NUMBER;
        hash = (53 * hash) + getBirthplaceList().hashCode();
      }
      if (getHobbiesCount() > 0) {
        hash = (37 * hash) + HOBBIES_FIELD_NUMBER;
        hash = (53 * hash) + getHobbiesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static User parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static User parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(User prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code data.User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:data.User)
        UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoDTO.internal_static_data_User_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoDTO.internal_static_data_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                User.class, Builder.class);
      }

      // Construct using data.ProtoDTO.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        login_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        birthday_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        birthplace_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        hobbies_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoDTO.internal_static_data_User_descriptor;
      }

      @Override
      public User getDefaultInstanceForType() {
        return User.getDefaultInstance();
      }

      @Override
      public User build() {
        User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public User buildPartial() {
        User result = new User(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.login_ = login_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          birthday_ = birthday_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.birthday_ = birthday_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          birthplace_ = birthplace_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.birthplace_ = birthplace_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          hobbies_ = hobbies_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.hobbies_ = hobbies_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof User) {
          return mergeFrom((User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(User other) {
        if (other == User.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasLogin()) {
          bitField0_ |= 0x00000002;
          login_ = other.login_;
          onChanged();
        }
        if (!other.birthday_.isEmpty()) {
          if (birthday_.isEmpty()) {
            birthday_ = other.birthday_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureBirthdayIsMutable();
            birthday_.addAll(other.birthday_);
          }
          onChanged();
        }
        if (!other.birthplace_.isEmpty()) {
          if (birthplace_.isEmpty()) {
            birthplace_ = other.birthplace_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureBirthplaceIsMutable();
            birthplace_.addAll(other.birthplace_);
          }
          onChanged();
        }
        if (!other.hobbies_.isEmpty()) {
          if (hobbies_.isEmpty()) {
            hobbies_ = other.hobbies_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureHobbiesIsMutable();
            hobbies_.addAll(other.hobbies_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        if (!hasId()) {
          return false;
        }
        if (!hasLogin()) {
          return false;
        }
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        User parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (User) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private Object login_ = "";
      /**
       * <code>required string login = 2;</code>
       */
      public boolean hasLogin() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string login = 2;</code>
       */
      public String getLogin() {
        Object ref = login_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            login_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string login = 2;</code>
       */
      public com.google.protobuf.ByteString
          getLoginBytes() {
        Object ref = login_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          login_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string login = 2;</code>
       */
      public Builder setLogin(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        login_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string login = 2;</code>
       */
      public Builder clearLogin() {
        bitField0_ = (bitField0_ & ~0x00000002);
        login_ = getDefaultInstance().getLogin();
        onChanged();
        return this;
      }
      /**
       * <code>required string login = 2;</code>
       */
      public Builder setLoginBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        login_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList birthday_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureBirthdayIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          birthday_ = new com.google.protobuf.LazyStringArrayList(birthday_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string birthday = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getBirthdayList() {
        return birthday_.getUnmodifiableView();
      }
      /**
       * <code>repeated string birthday = 3;</code>
       */
      public int getBirthdayCount() {
        return birthday_.size();
      }
      /**
       * <code>repeated string birthday = 3;</code>
       */
      public String getBirthday(int index) {
        return birthday_.get(index);
      }
      /**
       * <code>repeated string birthday = 3;</code>
       */
      public com.google.protobuf.ByteString
          getBirthdayBytes(int index) {
        return birthday_.getByteString(index);
      }
      /**
       * <code>repeated string birthday = 3;</code>
       */
      public Builder setBirthday(
              int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureBirthdayIsMutable();
        birthday_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string birthday = 3;</code>
       */
      public Builder addBirthday(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureBirthdayIsMutable();
        birthday_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string birthday = 3;</code>
       */
      public Builder addAllBirthday(
          Iterable<String> values) {
        ensureBirthdayIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, birthday_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string birthday = 3;</code>
       */
      public Builder clearBirthday() {
        birthday_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string birthday = 3;</code>
       */
      public Builder addBirthdayBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureBirthdayIsMutable();
        birthday_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList birthplace_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureBirthplaceIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          birthplace_ = new com.google.protobuf.LazyStringArrayList(birthplace_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string birthplace = 4;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getBirthplaceList() {
        return birthplace_.getUnmodifiableView();
      }
      /**
       * <code>repeated string birthplace = 4;</code>
       */
      public int getBirthplaceCount() {
        return birthplace_.size();
      }
      /**
       * <code>repeated string birthplace = 4;</code>
       */
      public String getBirthplace(int index) {
        return birthplace_.get(index);
      }
      /**
       * <code>repeated string birthplace = 4;</code>
       */
      public com.google.protobuf.ByteString
          getBirthplaceBytes(int index) {
        return birthplace_.getByteString(index);
      }
      /**
       * <code>repeated string birthplace = 4;</code>
       */
      public Builder setBirthplace(
              int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureBirthplaceIsMutable();
        birthplace_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string birthplace = 4;</code>
       */
      public Builder addBirthplace(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureBirthplaceIsMutable();
        birthplace_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string birthplace = 4;</code>
       */
      public Builder addAllBirthplace(
          Iterable<String> values) {
        ensureBirthplaceIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, birthplace_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string birthplace = 4;</code>
       */
      public Builder clearBirthplace() {
        birthplace_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string birthplace = 4;</code>
       */
      public Builder addBirthplaceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureBirthplaceIsMutable();
        birthplace_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList hobbies_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureHobbiesIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          hobbies_ = new com.google.protobuf.LazyStringArrayList(hobbies_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated string hobbies = 5;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getHobbiesList() {
        return hobbies_.getUnmodifiableView();
      }
      /**
       * <code>repeated string hobbies = 5;</code>
       */
      public int getHobbiesCount() {
        return hobbies_.size();
      }
      /**
       * <code>repeated string hobbies = 5;</code>
       */
      public String getHobbies(int index) {
        return hobbies_.get(index);
      }
      /**
       * <code>repeated string hobbies = 5;</code>
       */
      public com.google.protobuf.ByteString
          getHobbiesBytes(int index) {
        return hobbies_.getByteString(index);
      }
      /**
       * <code>repeated string hobbies = 5;</code>
       */
      public Builder setHobbies(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureHobbiesIsMutable();
        hobbies_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string hobbies = 5;</code>
       */
      public Builder addHobbies(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureHobbiesIsMutable();
        hobbies_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string hobbies = 5;</code>
       */
      public Builder addAllHobbies(
          Iterable<String> values) {
        ensureHobbiesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, hobbies_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string hobbies = 5;</code>
       */
      public Builder clearHobbies() {
        hobbies_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string hobbies = 5;</code>
       */
      public Builder addHobbiesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureHobbiesIsMutable();
        hobbies_.add(value);
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:data.User)
    }

    // @@protoc_insertion_point(class_scope:data.User)
    private static final User DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new User();
    }

    public static User getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<User>
        PARSER = new com.google.protobuf.AbstractParser<User>() {
      @Override
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new User(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<User> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    @Override
    public User getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DTOOrBuilder extends
      // @@protoc_insertion_point(interface_extends:data.DTO)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>required .data.User user = 2;</code>
     */
    boolean hasUser();
    /**
     * <code>required .data.User user = 2;</code>
     */
    User getUser();
    /**
     * <code>required .data.User user = 2;</code>
     */
    UserOrBuilder getUserOrBuilder();

    /**
     * <code>repeated string date = 3;</code>
     */
    java.util.List<String>
        getDateList();
    /**
     * <code>repeated string date = 3;</code>
     */
    int getDateCount();
    /**
     * <code>repeated string date = 3;</code>
     */
    String getDate(int index);
    /**
     * <code>repeated string date = 3;</code>
     */
    com.google.protobuf.ByteString
        getDateBytes(int index);

    /**
     * <code>repeated int32 price = 4;</code>
     */
    java.util.List<Integer> getPriceList();
    /**
     * <code>repeated int32 price = 4;</code>
     */
    int getPriceCount();
    /**
     * <code>repeated int32 price = 4;</code>
     */
    int getPrice(int index);
  }
  /**
   * Protobuf type {@code data.DTO}
   */
  public  static final class DTO extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:data.DTO)
      DTOOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DTO.newBuilder() to construct.
    private DTO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DTO() {
      id_ = 0;
      date_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      price_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DTO(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              User.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = user_.toBuilder();
              }
              user_ = input.readMessage(User.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(user_);
                user_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                date_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              date_.add(bs);
              break;
            }
            case 32: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                price_ = new java.util.ArrayList<Integer>();
                mutable_bitField0_ |= 0x00000008;
              }
              price_.add(input.readInt32());
              break;
            }
            case 34: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008) && input.getBytesUntilLimit() > 0) {
                price_ = new java.util.ArrayList<Integer>();
                mutable_bitField0_ |= 0x00000008;
              }
              while (input.getBytesUntilLimit() > 0) {
                price_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          date_ = date_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          price_ = java.util.Collections.unmodifiableList(price_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoDTO.internal_static_data_DTO_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoDTO.internal_static_data_DTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DTO.class, Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int USER_FIELD_NUMBER = 2;
    private User user_;
    /**
     * <code>required .data.User user = 2;</code>
     */
    public boolean hasUser() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .data.User user = 2;</code>
     */
    public User getUser() {
      return user_ == null ? User.getDefaultInstance() : user_;
    }
    /**
     * <code>required .data.User user = 2;</code>
     */
    public UserOrBuilder getUserOrBuilder() {
      return user_ == null ? User.getDefaultInstance() : user_;
    }

    public static final int DATE_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList date_;
    /**
     * <code>repeated string date = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getDateList() {
      return date_;
    }
    /**
     * <code>repeated string date = 3;</code>
     */
    public int getDateCount() {
      return date_.size();
    }
    /**
     * <code>repeated string date = 3;</code>
     */
    public String getDate(int index) {
      return date_.get(index);
    }
    /**
     * <code>repeated string date = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDateBytes(int index) {
      return date_.getByteString(index);
    }

    public static final int PRICE_FIELD_NUMBER = 4;
    private java.util.List<Integer> price_;
    /**
     * <code>repeated int32 price = 4;</code>
     */
    public java.util.List<Integer>
        getPriceList() {
      return price_;
    }
    /**
     * <code>repeated int32 price = 4;</code>
     */
    public int getPriceCount() {
      return price_.size();
    }
    /**
     * <code>repeated int32 price = 4;</code>
     */
    public int getPrice(int index) {
      return price_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUser()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getUser().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, getUser());
      }
      for (int i = 0; i < date_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, date_.getRaw(i));
      }
      for (int i = 0; i < price_.size(); i++) {
        output.writeInt32(4, price_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getUser());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < date_.size(); i++) {
          dataSize += computeStringSizeNoTag(date_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getDateList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < price_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(price_.get(i));
        }
        size += dataSize;
        size += 1 * getPriceList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof DTO)) {
        return super.equals(obj);
      }
      DTO other = (DTO) obj;

      boolean result = true;
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && (getId()
            == other.getId());
      }
      result = result && (hasUser() == other.hasUser());
      if (hasUser()) {
        result = result && getUser()
            .equals(other.getUser());
      }
      result = result && getDateList()
          .equals(other.getDateList());
      result = result && getPriceList()
          .equals(other.getPriceList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
      }
      if (hasUser()) {
        hash = (37 * hash) + USER_FIELD_NUMBER;
        hash = (53 * hash) + getUser().hashCode();
      }
      if (getDateCount() > 0) {
        hash = (37 * hash) + DATE_FIELD_NUMBER;
        hash = (53 * hash) + getDateList().hashCode();
      }
      if (getPriceCount() > 0) {
        hash = (37 * hash) + PRICE_FIELD_NUMBER;
        hash = (53 * hash) + getPriceList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static DTO parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DTO parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DTO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DTO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DTO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DTO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DTO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DTO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static DTO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static DTO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static DTO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DTO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(DTO prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code data.DTO}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:data.DTO)
        DTOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoDTO.internal_static_data_DTO_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoDTO.internal_static_data_DTO_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DTO.class, Builder.class);
      }

      // Construct using data.ProtoDTO.DTO.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getUserFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (userBuilder_ == null) {
          user_ = null;
        } else {
          userBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        date_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        price_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoDTO.internal_static_data_DTO_descriptor;
      }

      @Override
      public DTO getDefaultInstanceForType() {
        return DTO.getDefaultInstance();
      }

      @Override
      public DTO build() {
        DTO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public DTO buildPartial() {
        DTO result = new DTO(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (userBuilder_ == null) {
          result.user_ = user_;
        } else {
          result.user_ = userBuilder_.build();
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          date_ = date_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.date_ = date_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          price_ = java.util.Collections.unmodifiableList(price_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.price_ = price_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DTO) {
          return mergeFrom((DTO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DTO other) {
        if (other == DTO.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasUser()) {
          mergeUser(other.getUser());
        }
        if (!other.date_.isEmpty()) {
          if (date_.isEmpty()) {
            date_ = other.date_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureDateIsMutable();
            date_.addAll(other.date_);
          }
          onChanged();
        }
        if (!other.price_.isEmpty()) {
          if (price_.isEmpty()) {
            price_ = other.price_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensurePriceIsMutable();
            price_.addAll(other.price_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        if (!hasId()) {
          return false;
        }
        if (!hasUser()) {
          return false;
        }
        if (!getUser().isInitialized()) {
          return false;
        }
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DTO parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DTO) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private User user_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          User, User.Builder, UserOrBuilder> userBuilder_;
      /**
       * <code>required .data.User user = 2;</code>
       */
      public boolean hasUser() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .data.User user = 2;</code>
       */
      public User getUser() {
        if (userBuilder_ == null) {
          return user_ == null ? User.getDefaultInstance() : user_;
        } else {
          return userBuilder_.getMessage();
        }
      }
      /**
       * <code>required .data.User user = 2;</code>
       */
      public Builder setUser(User value) {
        if (userBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          user_ = value;
          onChanged();
        } else {
          userBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .data.User user = 2;</code>
       */
      public Builder setUser(
          User.Builder builderForValue) {
        if (userBuilder_ == null) {
          user_ = builderForValue.build();
          onChanged();
        } else {
          userBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .data.User user = 2;</code>
       */
      public Builder mergeUser(User value) {
        if (userBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              user_ != null &&
              user_ != User.getDefaultInstance()) {
            user_ =
              User.newBuilder(user_).mergeFrom(value).buildPartial();
          } else {
            user_ = value;
          }
          onChanged();
        } else {
          userBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .data.User user = 2;</code>
       */
      public Builder clearUser() {
        if (userBuilder_ == null) {
          user_ = null;
          onChanged();
        } else {
          userBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .data.User user = 2;</code>
       */
      public User.Builder getUserBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getUserFieldBuilder().getBuilder();
      }
      /**
       * <code>required .data.User user = 2;</code>
       */
      public UserOrBuilder getUserOrBuilder() {
        if (userBuilder_ != null) {
          return userBuilder_.getMessageOrBuilder();
        } else {
          return user_ == null ?
              User.getDefaultInstance() : user_;
        }
      }
      /**
       * <code>required .data.User user = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          User, User.Builder, UserOrBuilder>
          getUserFieldBuilder() {
        if (userBuilder_ == null) {
          userBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              User, User.Builder, UserOrBuilder>(
                  getUser(),
                  getParentForChildren(),
                  isClean());
          user_ = null;
        }
        return userBuilder_;
      }

      private com.google.protobuf.LazyStringList date_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureDateIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          date_ = new com.google.protobuf.LazyStringArrayList(date_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string date = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getDateList() {
        return date_.getUnmodifiableView();
      }
      /**
       * <code>repeated string date = 3;</code>
       */
      public int getDateCount() {
        return date_.size();
      }
      /**
       * <code>repeated string date = 3;</code>
       */
      public String getDate(int index) {
        return date_.get(index);
      }
      /**
       * <code>repeated string date = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDateBytes(int index) {
        return date_.getByteString(index);
      }
      /**
       * <code>repeated string date = 3;</code>
       */
      public Builder setDate(
              int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDateIsMutable();
        date_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string date = 3;</code>
       */
      public Builder addDate(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDateIsMutable();
        date_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string date = 3;</code>
       */
      public Builder addAllDate(
          Iterable<String> values) {
        ensureDateIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, date_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string date = 3;</code>
       */
      public Builder clearDate() {
        date_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string date = 3;</code>
       */
      public Builder addDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDateIsMutable();
        date_.add(value);
        onChanged();
        return this;
      }

      private java.util.List<Integer> price_ = java.util.Collections.emptyList();
      private void ensurePriceIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          price_ = new java.util.ArrayList<Integer>(price_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated int32 price = 4;</code>
       */
      public java.util.List<Integer>
          getPriceList() {
        return java.util.Collections.unmodifiableList(price_);
      }
      /**
       * <code>repeated int32 price = 4;</code>
       */
      public int getPriceCount() {
        return price_.size();
      }
      /**
       * <code>repeated int32 price = 4;</code>
       */
      public int getPrice(int index) {
        return price_.get(index);
      }
      /**
       * <code>repeated int32 price = 4;</code>
       */
      public Builder setPrice(
          int index, int value) {
        ensurePriceIsMutable();
        price_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 price = 4;</code>
       */
      public Builder addPrice(int value) {
        ensurePriceIsMutable();
        price_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 price = 4;</code>
       */
      public Builder addAllPrice(
          Iterable<? extends Integer> values) {
        ensurePriceIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, price_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 price = 4;</code>
       */
      public Builder clearPrice() {
        price_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:data.DTO)
    }

    // @@protoc_insertion_point(class_scope:data.DTO)
    private static final DTO DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new DTO();
    }

    public static DTO getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<DTO>
        PARSER = new com.google.protobuf.AbstractParser<DTO>() {
      @Override
      public DTO parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DTO(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DTO> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<DTO> getParserForType() {
      return PARSER;
    }

    @Override
    public DTO getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_User_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_User_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_DTO_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_DTO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\034src/main/java/data/dto.proto\022\004data\"X\n\004" +
      "User\022\n\n\002id\030\001 \002(\005\022\r\n\005login\030\002 \002(\t\022\020\n\010birth" +
      "day\030\003 \003(\t\022\022\n\nbirthplace\030\004 \003(\t\022\017\n\007hobbies" +
      "\030\005 \003(\t\"H\n\003DTO\022\n\n\002id\030\001 \002(\005\022\030\n\004user\030\002 \002(\0132" +
      "\n.data.User\022\014\n\004date\030\003 \003(\t\022\r\n\005price\030\004 \003(\005" +
      "B\020\n\004dataB\010ProtoDTO"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_data_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_data_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_User_descriptor,
        new String[] { "Id", "Login", "Birthday", "Birthplace", "Hobbies", });
    internal_static_data_DTO_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_data_DTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_DTO_descriptor,
        new String[] { "Id", "User", "Date", "Price", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
